### ISSUE TITLE
Fix ms-rest-nodeauth interactiveLogin

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/ms-rest-js#156]
Seeing the following stack trace when attempting to use ms-rest-nodeauth's interactiveLogin method:

```
Error: Entry not found in cache.
    at Logger.createError (/Users/rigibson/src/ms-rest-nodeauth/node_modules/adal-node/lib/log.js:216:13)
    at TokenRequest.<anonymous> (/Users/rigibson/src/ms-rest-nodeauth/node_modules/adal-node/lib/token-request.js:526:40)
    at /Users/rigibson/src/ms-rest-nodeauth/node_modules/adal-node/lib/token-request.js:148:20
    at /Users/rigibson/src/ms-rest-nodeauth/node_modules/adal-node/lib/cache-driver.js:361:7
    at /Users/rigibson/src/ms-rest-nodeauth/node_modules/adal-node/lib/cache-driver.js:231:5
    at /Users/rigibson/src/ms-rest-nodeauth/node_modules/adal-node/lib/cache-driver.js:163:5
    at MemoryCache.find (/Users/rigibson/src/ms-rest-nodeauth/node_modules/adal-node/lib/memory-cache.js:89:3)
    at CacheDriver._find (/Users/rigibson/src/ms-rest-nodeauth/node_modules/adal-node/lib/cache-driver.js:140:15)
    at CacheDriver._getPotentialEntries (/Users/rigibson/src/ms-rest-nodeauth/node_modules/adal-node/lib/cache-driver.js:161:8)
    at CacheDriver._loadSingleEntryFromCache (/Users/rigibson/src/ms-rest-nodeauth/node_modules/adal-node/lib/cache-driver.js:194:8)
```

Depends on https://github.com/Azure/ms-rest-nodeauth/issues/5.

**Comment by amarzavery** [comment]
@kpajdzik - Please take a look at this issue as well.

**Comment by kpajdzik** [comment]
Fixed by https://github.com/Azure/ms-rest-nodeauth/pull/8

**Comment by CYoderDev** [comment]
This is still an issue as of 4/23/2021. Using interactive login with ms-rest-nodeauth v3.0.9 -- it appears to only happen whenever the response returns a non 2xx status. In my case one 404 would result in this error for the next call.

It does not happen with service principals.

**Comment by jeremymeng** [comment]
@sadasant is this an issue in ms-rest-nodeauth or ms-rest-js? If former, could we transfer the issue to ms-rest-nodeauth repo?
